flowchart LR
    A["IDLE"] --> B["Pressed?"]
    B --> C(("Yes")) & D(("No"))
    D --> A
    C --> E["PRESSED"]
    E --> F["Next Frame"]
    F --> G["HELD"]
    G --> H["Next Frame"]
    H --> Z["Pressed?"]
    Z --> J(("No")) & I(("Yes"))
    I --> G
    J --> K["RELEASED"]
    K --> L["Next Frame"]
    L --> A
    A@{ shape: paper-tape}
    B@{ shape: hex}
    E@{ shape: paper-tape}
    G@{ shape: paper-tape}
    Z@{ shape: hex}
    K@{ shape: paper-tape}
