name: Documentation

on:
  push:
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen build site
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'docs/'
            doxyfile-path: 'docs/Doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
